# Generated by Django 5.2 on 2025-04-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("excel_matcher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="processedfile",
            name="processing_mode",
            field=models.CharField(
                choices=[
                    ("SELF_LEARNING", "自学习标准化"),
                    ("REFERENCE", "参照标准匹配"),
                ],
                default="SELF_LEARNING",
                max_length=20,
                verbose_name="处理模式",
            ),
        ),
        migrations.AddField(
            model_name="processedfile",
            name="reference_column",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="标准参照列"
            ),
        ),
    ]
