# Generated by Django 5.2 on 2025-04-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProcessedFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_file", models.CharField(max_length=255)),
                ("processed_file", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("columns_processed", models.JSONField(default=list)),
            ],
            options={
                "verbose_name": "处理文件记录",
                "verbose_name_plural": "处理文件记录",
            },
        ),
        migrations.CreateModel(
            name="FuzzyMatchPattern",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("column_name", models.CharField(max_length=100, verbose_name="列名")),
                (
                    "original_pattern",
                    models.CharField(max_length=255, verbose_name="原始模式"),
                ),
                (
                    "standardized_value",
                    models.CharField(max_length=255, verbose_name="标准化值"),
                ),
            ],
            options={
                "verbose_name": "模糊匹配模式",
                "verbose_name_plural": "模糊匹配模式",
                "unique_together": {("column_name", "original_pattern")},
            },
        ),
    ]
